apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: twistlock-scan
spec:
  params:
    - name: pathToDockerFile
      type: string
      description: The path to the dockerfile to build
      default: $(resources.inputs.docker.path)/Dockerfile
    - name: pathToContext
      type: string
      description: |
        The build context used by Kaniko
        (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)        
      default: $(resources.inputs.docker.path)
    
  resources:
    inputs:
      - name: docker
        type: git
    outputs:
      - name: Twistlock-Image
        type: image
  steps:
    - name: built
      image: gcr.io/kaniko-project/executor:v0.17.1
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.pathToDockerFile)
        - --destination=$(resources.outputs.Twistlock-Image.url)
        - --context=$(params. pathToContext)
    